
data:
    type: "all" # "hwp" 또는 "pdf", "all"
    folder_path: "data/files"
    data_list_path: "data/data_list.csv"
    apply_ocr: False # True/ False
    re: # 전처리?

chunk:
    spliter: # RecursiveCharacterTextSplitter, TokenTextSplitter
    size:
    overlap:

embedding:
    type: "langchain" # 
    model: "openai" # "openai", "cohere", "huggingface"
    model_path: 
    vector_db_path: "data"

query:
    type: "retrieval" # "retrieval", "generation"
    query: "배드민턴장 및 탁구장 예약방법"
    top_k: 3
    filter: # {"key": "value"}
    context: # {"key": "value"}
    prompt: # {"key": "value"}

retrieval:

generation:

model:
    type: 
    model_path: 
    temperature: 
    max_tokens: 
    top_p: 
    top_k: 
    n: 
    stop: 

# settings
settings:
    use_gpu: True
    verbose: False
