
data:
    type: "all" # "hwp" 또는 "pdf", "all"
    limit: 5 # 최대 몇개까지 1 ~ 100 
    folder_path: "data/files"
    data_list_path: "data/data_list.csv"
    apply_ocr: False # True/ False
    re: # 전처리?

chunk:
    splitter: "recursive" # "recursive", "token"
    size: 300
    overlap: 50

embedding:
    type: "langchain"
    model: "jhgan/ko-sroberta-multitask"  # KoAlpaca는 generation용, 임베딩엔 STS 기반 모델 사용
    model_path: null                      # Hugging Face에서 다운로드하므로 경로는 null
    vector_db_path: "data"   # FAISS 벡터 저장 경로

query:
    type: "retrieval" # "retrieval", "generation"
    question: "대학교와 관련된 사업은 뭐가 있어?"
    top_k: 3
    filter: # {"key": "value"}
    context: # {"key": "value"}
    prompt: # {"key": "value"}

retrieval:
    search_type: "similarity"  # "similarity", "mmr", etc.

generation:

model:
    type: 
    model_path: 
    temperature: 
    max_tokens: 
    top_p: 
    top_k: 
    n: 
    stop: 

# settings
settings:
    use_gpu: True
    verbose: False