
data:
    folder_path: "data/files"
    data_list_path: "data/data_list.csv"
    limit: 100 # 최대 몇개까지 1 ~ 100 
    file_type: "all" # "hwp" 또는 "pdf", "all"
    apply_ocr: False # True/ False
    splitter: "recursive" # "recursive", "token"
    chunk_size: 300
    chunk_overlap: 50

embedding:
    # openai 사용시 "text-embedding-3-small" 권장
    embed_model: "nlpai-lab/KoE5" #"sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2", "openai", "cohere", "huggingface"
    db_type: "faiss" # "faiss", "chorma"
    vector_db_path: "data"

retriever:
    query: "배드민턴장 및 탁구장 예약방법"
    top_k: 3

generator:
    model_type: ""
    model_name: ""
    max_length: 512
    
# settings
settings:
    verbose: True