settings:
    verbose: False
    project_root: ""

data:
    folder_path: "data/files"
    data_list_path: "data/data_list.csv"
    top_k: 5 # 최대 몇개까지 1 ~ 100 
    file_type: "all" # "hwp" 또는 "pdf", "all"
    apply_ocr: False # True/ False
    splitter: "section" # "recursive", "token", "section"
    chunk_size: 1000            # KoE5는 허용 토큰이 많은 편이기에, chunk_size를 높일 수 있다.
    chunk_overlap: 250 

embedding:
    # openai 사용시 "text-embedding-3-small" 권장
    embed_model: "openai" #"sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    db_type: "faiss" # "faiss", "chorma"
    vector_db_path: "data/vector_db"

retriever:
    search_type: "hybrid" # "similarity", "hybrid"
    query: ""
    top_k: 10
    rerank: True # True/ False
    rerank_top_k: 5

generator:
    model_type: "openai" # "huggingface", "openai"
    model_name: "gpt-4.1-nano" # "microsoft/Phi-4-mini-instruct", "gpt-4.1-mini", "gpt-4.1-nano"
    max_length: 512
    use_quantization: True

chat_history: