
data:
    type: "all" # "hwp" 또는 "pdf", "all"
    limit: 100 # 최대 몇개까지 1 ~ 100 
    folder_path: "data/files"
    data_list_path: "data/data_list.csv"
    apply_ocr: False # True/ False
    re: # 전처리?

chunk:
    splitter: "recursive" # "recursive", "token"
    size: 300
    overlap: 50

embedding:
    type: "langchain" # 
    model: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2" #"nlpai-lab/KoE5", "openai", "cohere", "huggingface"
    model_path: 
    vector_db_path: "data"
    index_name: "hwp_faiss_index"

query:
    type: "retrieval" # "retrieval", "generation"
    question: "인공지능(AI) 교육으로 IT 융합 인재 양성"
    top_k: 5
    filter: # {"key": "value"}
    context: # {"key": "value"}
    prompt: # {"key": "value"}

retrieval:
    method: "similarity"  # "hybrid", "similarity"

generation:

model:
    type: 
    model_path: 
    temperature: 
    max_tokens: 
    top_p: 
    top_k: 
    n: 
    stop: 

# settings
settings:
    use_gpu: True
    verbose: False