
data:
    type: "all" # "hwp" 또는 "pdf", "all"
    limit: 100 # 최대 몇개까지 1 ~ 100 
    folder_path: "data/files"
    data_list_path: "data/data_list.csv"
    apply_ocr: False # True/ False
    re: # 전처리?

chunk:
    splitter: "recursive" # "recursive", "token"
    size: 1000            # KoE5는 허용 토큰이 많은 편이기에, chunk_size를 높일 수 있다.
    overlap: 100 

embedding:
    type: "langchain" # 
    db_type: "faiss" # "faiss", "chorma"
    # openai 사용시 "text-embedding-3-small" 권장
    model: "nlpai-lab/KoE5" #"sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2", "openai", "cohere", "huggingface"
    model_path: 
    vector_db_path: "data"
    index_name: "hwp_faiss_index"

query:
    type: "retrieval" # "retrieval", "generation"
    question: "배드민턴장 및 탁구장 예약방법"
    top_k: 6
    filter: # {"key": "value"}
    context: # {"key": "value"}
    prompt: # {"key": "value"}

retrieval:
    search_type: "similarity" # "hybrid"

generation:

model:
    type: 
    model_path: 
    temperature: 
    max_tokens: 
    top_p: 
    top_k: 
    n: 
    stop: 

# settings
settings:
    verbose: True