
data:
    folder_path: "data/files"
    data_list_path: "data/data_list.csv"
    top_k: 5 # 최대 몇개까지 1 ~ 100 
    file_type: "all" # "hwp" 또는 "pdf", "all"
    apply_ocr: False # True/ False
    splitter: "recursive" # "recursive", "token"
    chunk_size: 1000            # KoE5는 허용 토큰이 많은 편이기에, chunk_size를 높일 수 있다.
    chunk_overlap: 100 

embedding:
    # openai 사용시 "text-embedding-3-small" 권장
    embed_model: "nlpai-lab/KoE5" #"sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2", "openai", "cohere", "huggingface"
    db_type: "faiss" # "faiss", "chorma"
    vector_db_path: "data"

retriever:
    search_type: "similarity" # "similarity", "hybrid"
    query: "배드민턴장 및 탁구장 예약방법"
    top_k: 5
    rerank: True # True/ False
    rerank_top_k: 3

generator:
    model_type: "huggingface"
    model_name: "microsoft/Phi-4-mini-instruct"
    max_length: 512
    use_quantization: False

# settings
settings:
    verbose: True