name: myenv
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - fastapi
  - uvicorn
  - pyyaml
  - pillow
  - python-dotenv
  - pydantic
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - langchain
      - langchain-openai
      - langchain-community
      - langchain-huggingface
      - langchain-chroma
      - langchain-text-splitters
      - langchain-teddynote
      - langsmith
      - transformers
      - sentence-transformers
      - openai
      - faiss-cpu
      - pymupdf
      - streamlit
      - requests
      - tabulate
      - easyocr
      - bitsandbytes
      - accelerate
      - gunicorn